# Generated by Django 3.2.7 on 2021-09-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='user',
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=400)),
                ('Status', models.CharField(max_length=20)),
                ('Duedate', models.DateField()),
                ('Member', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Under_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=400)),
                ('Status', models.CharField(max_length=20)),
                ('Duedate', models.DateField()),
                ('Under_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.list')),
                ('Under_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
        ),
    ]
